### ISSUE TITLE
calling scrollTo on nearby items uses the estimated position rather than the known one (using smooth scrolling)

### ISSUE THREAD

**Issue by alexander-riss** [adobe/uxp-optimized#22]
this has the effect of scrolling to the wrong position first and then scrolling back to the actual position although the positions should be known by that time(eg. also happens when scrolling to the same element in a list repeatedly)

**Comment by krisnye** [comment]
This should be fixed in 1.1.2

**Comment by alexander-riss** [comment]
still seeing the effect in 1.1.2
